choco install DotNet3.5 -y
choco install DotNet4.5 -y
choco install DotNet4.6 -y
choco install 7zip.install -y
choco install discord -y
choco install keepass.install -y
choco install Firefox -y
choco install thunderbird -y
choco install speedfan -y
choco install steam -y
choco install uplay -y
choco install playnite -y
choco install steam-cleaner -y
choco install origin -y
choco install SublimeText3 -y
choco install SublimeText3.PackageControl -y